from .auto_align import NODE_CLASS_MAPPINGS as AUTO_ALIGN_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as AUTO_ALIGN_DISPLAY_MAPPINGS
from .charon_camera import NODE_CLASS_MAPPINGS as CAMERA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CAMERA_DISPLAY_MAPPINGS
from .glb_to_obj import NODE_CLASS_MAPPINGS as GLB_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GLB_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **AUTO_ALIGN_MAPPINGS,
    **CAMERA_MAPPINGS,
    **GLB_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **AUTO_ALIGN_DISPLAY_MAPPINGS,
    **CAMERA_DISPLAY_MAPPINGS,
    **GLB_DISPLAY_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']