"""Embedded Nuke knob scripts used by Charon 3D tools."""

from __future__ import annotations

import os

from . import paths


_COVERAGE_CAMERA_GENERATE_SCRIPT = (
    "import math\n"
    "import nuke\n"
    "\n"
    "def _find_upstream(start_node, class_names, max_hops=32):\n"
    "    current = start_node\n"
    "    visited = set()\n"
    "    hops = 0\n"
    "    while current and hops < max_hops:\n"
    "        if current in visited:\n"
    "            break\n"
    "        visited.add(current)\n"
    "        try:\n"
    "            if current.Class() in class_names:\n"
    "                return current\n"
    "        except Exception:\n"
    "            pass\n"
    "        try:\n"
    "            current = current.input(0)\n"
    "        except Exception:\n"
    "            current = None\n"
    "        hops += 1\n"
    "    return None\n"
    "\n"
    "def _read_group_block(template_path):\n"
    "    try:\n"
    "        with open(template_path, \"r\") as handle:\n"
    "            content = handle.read()\n"
    "    except Exception as exc:\n"
    "        _debug(\"failed to read template: {0}\".format(exc))\n"
    "        return None\n"
    "\n"
    "    start_idx = content.find(\"\\nGroup {\")\n"
    "    if start_idx == -1:\n"
    "        if content.startswith(\"Group {\"):\n"
    "            start_idx = 0\n"
    "        else:\n"
    "            _debug(\"template missing Group block\")\n"
    "            return None\n"
    "    else:\n"
    "        start_idx += 1\n"
    "\n"
    "    end_idx = content.find(\"\\nend_group\", start_idx)\n"
    "    if end_idx == -1:\n"
    "        end_idx = content.find(\"end_group\", start_idx)\n"
    "        if end_idx == -1:\n"
    "            _debug(\"template missing end_group\")\n"
    "            return None\n"
    "        end_idx += len(\"end_group\")\n"
    "    else:\n"
    "        end_idx += len(\"\\nend_group\")\n"
    "    return content[start_idx:end_idx] + \"\\n\"\n"
    "\n"
    "def _paste_group(script_content):\n"
    "    import tempfile\n"
    "    temp_path = \"\"\n"
    "    try:\n"
    "        with tempfile.NamedTemporaryFile(mode=\"w\", suffix=\".nk\", delete=False) as handle:\n"
    "            handle.write(script_content)\n"
    "            temp_path = handle.name\n"
    "        for node in nuke.allNodes():\n"
    "            node.setSelected(False)\n"
    "        nuke.nodePaste(temp_path)\n"
    "        for node in nuke.selectedNodes():\n"
    "            if node.Class() == \"Group\":\n"
    "                return node\n"
    "    except Exception as exc:\n"
    "        _debug(\"paste failed: {0}\".format(exc))\n"
    "    finally:\n"
    "        if temp_path and os.path.exists(temp_path):\n"
    "            try:\n"
    "                os.unlink(temp_path)\n"
    "            except Exception:\n"
    "                pass\n"
    "    return None\n"
    "\n"
    "def _ensure_inputs(group):\n"
    "    group.begin()\n"
    "    try:\n"
    "        inputs = {node.name(): node for node in nuke.allNodes() if node.Class() == \"Input\"}\n"
    "\n"
    "        coverage_rig = inputs.get(\"coverage_rig\") or nuke.createNode(\"Input\")\n"
    "        coverage_rig.setName(\"coverage_rig\")\n"
    "        coverage_rig[\"number\"].setValue(2)\n"
    "\n"
    "        geo_input = inputs.get(\"geo\") or nuke.createNode(\"Input\")\n"
    "        geo_input.setName(\"geo\")\n"
    "        geo_input[\"number\"].setValue(3)\n"
    "\n"
    "        coverage_input = inputs.get(\"coverage_sheet\") or nuke.createNode(\"Input\")\n"
    "        coverage_input.setName(\"coverage_sheet\")\n"
    "        coverage_input[\"number\"].setValue(4)\n"
    "    finally:\n"
    "        group.end()\n"
    "\n"
    "def _ensure_update_knobs(group, update_script):\n"
    "    if not group.knob(\"charon_update_inputs\"):\n"
    "        update_knob = nuke.PyScript_Knob(\n"
    "            \"charon_update_inputs\",\n"
    "            \"Update Inputs\",\n"
    "            update_script or \"\",\n"
    "        )\n"
    "        update_knob.setFlag(nuke.STARTLINE)\n"
    "        group.addKnob(update_knob)\n"
    "\n"
    "    if not group.knob(\"charon_rig_cam_count\"):\n"
    "        cam_count_knob = nuke.Int_Knob(\"charon_rig_cam_count\", \"Projection Cameras Found\")\n"
    "        try:\n"
    "            cam_count_knob.setEnabled(False)\n"
    "        except Exception:\n"
    "            cam_count_knob.setFlag(nuke.DISABLED)\n"
    "        group.addKnob(cam_count_knob)\n"
    "\n"
    "def _current_cam_count(group):\n"
    "    group.begin()\n"
    "    try:\n"
    "        cams = [\n"
    "            node for node in nuke.allNodes()\n"
    "            if node.Class() in (\"Camera3\", \"Camera2\", \"Camera\")\n"
    "            and node.name().startswith(\"Cam\")\n"
    "        ]\n"
    "        return len(cams)\n"
    "    finally:\n"
    "        group.end()\n"
    "\n"
    "def _rebuild_for_count(group, count):\n"
    "    try:\n"
    "        count = int(count)\n"
    "    except Exception:\n"
    "        return None\n"
    "\n"
    "    template_path = os.path.join(TEMPLATE_DIR, \"projection_final_prep_{0}_cams.nk\".format(count))\n"
    "    template_path = os.path.normpath(template_path)\n"
    "    if not os.path.exists(template_path):\n"
    "        _debug(\"template not found: {0}\".format(template_path))\n"
    "        return None\n"
    "\n"
    "    script_content = _read_group_block(template_path)\n"
    "    if not script_content:\n"
    "        return None\n"
    "\n"
    "    def _collect_dependents(node):\n"
    "        deps = []\n"
    "        for other in nuke.allNodes(recurseGroups=False):\n"
    "            for i in range(other.inputs()):\n"
    "                try:\n"
    "                    if other.input(i) == node:\n"
    "                        deps.append((other, i))\n"
    "                except Exception:\n"
    "                    pass\n"
    "        return deps\n"
    "\n"
    "    def _unique_name(base_name, names=None):\n"
    "        if names is None:\n"
    "            names = {node.name() for node in nuke.allNodes(recurseGroups=False)}\n"
    "        if base_name not in names:\n"
    "            return base_name\n"
    "        index = 1\n"
    "        while True:\n"
    "            candidate = \"{0}{1}\".format(base_name, index)\n"
    "            if candidate not in names:\n"
    "                return candidate\n"
    "            index += 1\n"
    "\n"
    "    def _ensure_name_available(name, keep_node=None):\n"
    "        for other in nuke.allNodes(recurseGroups=False):\n"
    "            if other is keep_node:\n"
    "                continue\n"
    "            try:\n"
    "                if other.name() == name:\n"
    "                    try:\n"
    "                        other.setName(_unique_name(\"{0}_OLD\".format(name)))\n"
    "                    except Exception:\n"
    "                        pass\n"
    "            except Exception:\n"
    "                pass\n"
    "\n"
    "    input_nodes = [group.input(i) for i in range(group.inputs())]\n"
    "    old_name = group.name()\n"
    "    old_pos = (group.xpos(), group.ypos())\n"
    "    downstream = _collect_dependents(group)\n"
    "    update_script = \"\"\n"
    "    update_knob = group.knob(\"charon_update_inputs\")\n"
    "    if update_knob:\n"
    "        try:\n"
    "            update_script = update_knob.value()\n"
    "        except Exception:\n"
    "            update_script = \"\"\n"
    "\n"
    "    nuke.root().begin()\n"
    "    new_group = _paste_group(script_content)\n"
    "    if not new_group:\n"
    "        nuke.message(\"Failed to rebuild Final Prep group.\")\n"
    "        return None\n"
    "\n"
    "    for idx, inp in enumerate(input_nodes):\n"
    "        try:\n"
    "            new_group.setInput(idx, inp)\n"
    "        except Exception:\n"
    "            pass\n"
    "    try:\n"
    "        new_group.setXYpos(old_pos[0], old_pos[1])\n"
    "    except Exception:\n"
    "        pass\n"
    "\n"
    "    for dep, idx in downstream:\n"
    "        try:\n"
    "            dep.setInput(idx, new_group)\n"
    "        except Exception:\n"
    "            pass\n"
    "\n"
    "    _ensure_inputs(new_group)\n"
    "    _ensure_update_knobs(new_group, update_script)\n"
    "\n"
    "    old_group = group\n"
    "    try:\n"
    "        old_group.setName(\"{0}_OLD\".format(old_name), unique=True)\n"
    "    except Exception:\n"
    "        pass\n"
    "    try:\n"
    "        if new_group.name() != old_name:\n"
    "            new_group.setName(old_name)\n"
    "    except Exception:\n"
    "        try:\n"
    "            if new_group.name() != old_name:\n"
    "                new_group.setName(old_name, unique=True)\n"
    "        except Exception:\n"
    "            pass\n"
    "    try:\n"
    "        nuke.delete(old_group)\n"
    "    except Exception:\n"
    "        pass\n"
    "    return new_group\n"
    "\n"
    "def _value_to_count(value):\n"
    "    choices = [2, 4, 6, 8]\n"
    "    if isinstance(value, (int, float)):\n"
    "        idx = int(value)\n"
    "        if 0 <= idx < len(choices):\n"
    "            return choices[idx]\n"
    "    text = str(value).strip()\n"
    "    if text.isdigit():\n"
    "        candidate = int(text)\n"
    "        if candidate in choices:\n"
    "            return candidate\n"
    "    return 8\n"
    "\n"
    "def _run():\n"
    "    group = nuke.thisNode()\n"
    "\n"
    "    count = 8\n"
    "    try:\n"
    "        knob = group.knob(\"charon_cam_count\")\n"
    "        if knob is not None:\n"
    "            count = _value_to_count(knob.value())\n"
    "    except Exception:\n"
    "        pass\n"
    "\n"
    "    raw_init_cam = group.input(0)\n"
    "    geo_source = group.input(1)\n"
    "\n"
    "    init_cam = _find_upstream(raw_init_cam, (\"Camera3\", \"Camera2\", \"Camera\"))\n"
    "    if not init_cam:\n"
    "        nuke.message(\"Connect init_cam (Camera) to input 0.\")\n"
    "        return\n"
    "    if not geo_source:\n"
    "        nuke.message(\"Connect geo to input 1.\")\n"
    "        return\n"
    "\n"
    "    target_raw = init_cam.input(1)\n"
    "    target = _find_upstream(target_raw, (\"Axis3\", \"Axis2\", \"Axis\"))\n"
    "    if not target:\n"
    "        nuke.message(\"Connect a Target Axis to init_cam input 1.\")\n"
    "        return\n"
    "\n"
    "    pivot = target[\"translate\"].value()\n"
    "    start_pos = init_cam[\"translate\"].value()\n"
    "\n"
    "    rx = start_pos[0] - pivot[0]\n"
    "    ry = start_pos[1] - pivot[1]\n"
    "    rz = start_pos[2] - pivot[2]\n"
    "\n"
    "    root = nuke.root()\n"
    "    current_group = nuke.thisGroup()\n"
    "    root.begin()\n"
    "    original_selection = list(nuke.selectedNodes())\n"
    "    for n in original_selection:\n"
    "        n.setSelected(False)\n"
    "    try:\n"
    "        init_cam.setSelected(True)\n"
    "        nuke.nodeCopy(\"%clipboard%\")\n"
    "    finally:\n"
    "        init_cam.setSelected(False)\n"
    "        for n in original_selection:\n"
    "            try:\n"
    "                n.setSelected(True)\n"
    "            except Exception:\n"
    "                pass\n"
    "        if current_group and current_group is not root:\n"
    "            current_group.begin()\n"
    "\n"
    "    group.begin()\n"
    "    try:\n"
    "        input_cam = nuke.toNode(\"init_cam\")\n"
    "        input_geo = nuke.toNode(\"geo\")\n"
    "\n"
    "        inputs = [node for node in nuke.allNodes() if node.Class() == \"Input\"]\n"
    "        if input_cam is None:\n"
    "            for node in inputs:\n"
    "                if node is not input_geo:\n"
    "                    input_cam = node\n"
    "                    break\n"
    "        if input_geo is None:\n"
    "            for node in inputs:\n"
    "                if node is not input_cam:\n"
    "                    input_geo = node\n"
    "                    break\n"
    "\n"
    "        protected = set(node for node in (input_cam, input_geo) if node is not None)\n"
    "        for node in list(nuke.allNodes()):\n"
    "            if node in protected:\n"
    "                continue\n"
    "            nuke.delete(node)\n"
    "\n"
    "        if input_cam is None:\n"
    "            input_cam = nuke.createNode(\"Input\")\n"
    "        input_cam.setName(\"init_cam\")\n"
    "        input_cam[\"number\"].setValue(0)\n"
    "        input_cam.setXYpos(0, 0)\n"
    "\n"
    "        if input_geo is None:\n"
    "            input_geo = nuke.createNode(\"Input\")\n"
    "        input_geo.setName(\"geo\")\n"
    "        input_geo[\"number\"].setValue(1)\n"
    "        input_geo.setXYpos(0, 120)\n"
    "\n"
    "        dot_geo = nuke.createNode(\"Dot\")\n"
    "        dot_geo.setInput(0, input_geo)\n"
    "        dot_geo.setXYpos(input_geo.xpos() + 120, input_geo.ypos() + 20)\n"
    "\n"
    "        tex_const = nuke.createNode(\"Constant\")\n"
    "        tex_const.setName(\"BaseGray\")\n"
    "        tex_const[\"color\"].setValue([1, 1, 1, 1])\n"
    "        tex_const.setXYpos(input_geo.xpos() + 200, input_geo.ypos())\n"
    "\n"
    "        tex_wire = nuke.createNode(\"Wireframe\")\n"
    "        tex_wire.setInput(0, tex_const)\n"
    "        tex_wire[\"operation\"].setValue(\"over\")\n"
    "        tex_wire[\"line_width\"].setValue(0.12)\n"
    "        tex_wire[\"line_color\"].setValue([0.36, 0.36, 0.36, 1])\n"
    "        tex_wire.setXYpos(tex_const.xpos(), tex_const.ypos() + 110)\n"
    "\n"
    "        apply_mat = nuke.createNode(\"ApplyMaterial\")\n"
    "        apply_mat.setInput(0, dot_geo)\n"
    "        apply_mat.setInput(1, tex_wire)\n"
    "        apply_mat.setXYpos(input_geo.xpos() + 200, input_geo.ypos() + 220)\n"
    "\n"
    "        dot_mat = nuke.createNode(\"Dot\")\n"
    "        dot_mat.setInput(0, apply_mat)\n"
    "        dot_mat.setXYpos(apply_mat.xpos() + 80, apply_mat.ypos() + 140)\n"
    "\n"
    "        int_target = nuke.createNode(\"Axis3\")\n"
    "        int_target.setName(\"Target\")\n"
    "        int_target[\"translate\"].setValue(pivot)\n"
    "        int_target.setXYpos(-200, input_geo.ypos() + 220)\n"
    "\n"
    "        step = 360.0 / float(count)\n"
    "        angles = [int(round(step * i)) for i in range(count)]\n"
    "\n"
    "        render_outputs = []\n"
    "        base_x = 400\n"
    "        x_step = 250\n"
    "        y_cam = 240\n"
    "        y_scan = 460\n"
    "        y_merge = 580\n"
    "\n"
    "        for i, yaw in enumerate(angles):\n"
    "            name = \"Init\" if yaw == 0 else str(int(yaw))\n"
    "            x_pos = base_x + (i * x_step)\n"
    "\n"
    "            nuke.nodePaste(\"%clipboard%\")\n"
    "            cam = nuke.selectedNode()\n"
    "            cam.setName(f\"Cam{name}\")\n"
    "            cam.setInput(1, int_target)\n"
    "            cam[\"rotate\"].setValue([0, 0, 0])\n"
    "\n"
    "            rad_yaw = math.radians(float(yaw))\n"
    "            nx = rx * math.cos(rad_yaw) - rz * math.sin(rad_yaw)\n"
    "            nz = rx * math.sin(rad_yaw) + rz * math.cos(rad_yaw)\n"
    "            cam[\"translate\"].setValue([pivot[0] + nx, pivot[1] + ry, pivot[2] + nz])\n"
    "            cam.setXYpos(x_pos, y_cam)\n"
    "\n"
    "            scanline = nuke.createNode(\"ScanlineRender\")\n"
    "            scanline.setInput(1, dot_mat)\n"
    "            scanline.setInput(2, cam)\n"
    "            scanline.setXYpos(x_pos, y_scan)\n"
    "\n"
    "            bg = nuke.createNode(\"Constant\")\n"
    "            bg.setName(\"BG_Constant\")\n"
    "            bg[\"channels\"].setValue(\"rgb\")\n"
    "            bg[\"color\"].setValue([0.36, 0.36, 0.36, 1])\n"
    "            bg.setXYpos(x_pos + 100, y_scan)\n"
    "\n"
    "            merge = nuke.createNode(\"Merge2\")\n"
    "            merge.setInput(1, scanline)\n"
    "            merge.setInput(0, bg)\n"
    "            merge.setXYpos(x_pos, y_merge)\n"
    "\n"
    "            render_outputs.append(merge)\n"
    "\n"
    "        columns = max(1, int(count))\n"
    "        rows = int(math.ceil(float(count) / float(columns)))\n"
    "\n"
    "        contact = nuke.createNode(\"ContactSheet\")\n"
    "        contact_width = columns * 1024\n"
    "        contact_height = rows * 1024\n"
    "        contact[\"width\"].setValue(contact_width)\n"
    "        contact[\"height\"].setValue(contact_height)\n"
    "        contact[\"rows\"].setValue(rows)\n"
    "        contact[\"columns\"].setValue(columns)\n"
    "        contact[\"roworder\"].setValue(\"TopBottom\")\n"
    "        contact[\"gap\"].setValue(10)\n"
    "        for i, node in enumerate(render_outputs):\n"
    "            contact.setInput(i, node)\n"
    "        contact.setXYpos(base_x, 780)\n"
    "\n"
    "        output = nuke.createNode(\"Output\")\n"
    "        output.setInput(0, contact)\n"
    "        output.setXYpos(base_x, 900)\n"
    "    finally:\n"
    "        group.end()\n"
    "\n"
    "_run()\n"
)


def coverage_camera_generate_script() -> str:
    return _COVERAGE_CAMERA_GENERATE_SCRIPT


_FINAL_PREP_UPDATE_SCRIPT = (
    "import math\n"
    "import os\n"
    "import nuke\n"
    "\n"
    "TEMPLATE_DIR = r\"__TEMPLATE_DIR__\"\n"
    "\n"
    "_DEBUG = False\n"
    "\n"
    "def _debug(message):\n"
    "    if _DEBUG:\n"
    "        print(\"[FinalPrep] \" + message)\n"
    "\n"
    "def _angle_from_name(name):\n"
    "    if name == \"CamInit\":\n"
    "        return 0.0\n"
    "    if name.startswith(\"Cam\"):\n"
    "        suffix = name[3:]\n"
    "        if suffix.isdigit():\n"
    "            return float(suffix)\n"
    "    return None\n"
    "\n"
    "def _angle_from_position(pos, pivot):\n"
    "    dx = pos[0] - pivot[0]\n"
    "    dz = pos[2] - pivot[2]\n"
    "    angle = math.degrees(math.atan2(dz, dx))\n"
    "    if angle < 0:\n"
    "        angle += 360.0\n"
    "    return angle\n"
    "\n"
    "def _find_upstream(start_node, class_names, max_hops=32):\n"
    "    current = start_node\n"
    "    visited = set()\n"
    "    hops = 0\n"
    "    while current and hops < max_hops:\n"
    "        if current in visited:\n"
    "            break\n"
    "        visited.add(current)\n"
    "        try:\n"
    "            if current.Class() in class_names:\n"
    "                return current\n"
    "        except Exception:\n"
    "            pass\n"
    "        try:\n"
    "            current = current.input(0)\n"
    "        except Exception:\n"
    "            current = None\n"
    "        hops += 1\n"
    "    return None\n"
    "\n"
    "def _read_group_block(template_path):\n"
    "    try:\n"
    "        with open(template_path, \"r\") as handle:\n"
    "            content = handle.read()\n"
    "    except Exception as exc:\n"
    "        _debug(\"failed to read template: {0}\".format(exc))\n"
    "        return None\n"
    "\n"
    "    start_idx = content.find(\"\\nGroup {\")\n"
    "    if start_idx == -1:\n"
    "        if content.startswith(\"Group {\"):\n"
    "            start_idx = 0\n"
    "        else:\n"
    "            _debug(\"template missing Group block\")\n"
    "            return None\n"
    "    else:\n"
    "        start_idx += 1\n"
    "\n"
    "    end_idx = content.find(\"\\nend_group\", start_idx)\n"
    "    if end_idx == -1:\n"
    "        end_idx = content.find(\"end_group\", start_idx)\n"
    "        if end_idx == -1:\n"
    "            _debug(\"template missing end_group\")\n"
    "            return None\n"
    "        end_idx += len(\"end_group\")\n"
    "    else:\n"
    "        end_idx += len(\"\\nend_group\")\n"
    "    return content[start_idx:end_idx] + \"\\n\"\n"
    "\n"
    "def _paste_group(script_content):\n"
    "    import tempfile\n"
    "    temp_path = \"\"\n"
    "    try:\n"
    "        with tempfile.NamedTemporaryFile(mode=\"w\", suffix=\".nk\", delete=False) as handle:\n"
    "            handle.write(script_content)\n"
    "            temp_path = handle.name\n"
    "        for node in nuke.allNodes():\n"
    "            node.setSelected(False)\n"
    "        nuke.nodePaste(temp_path)\n"
    "        for node in nuke.selectedNodes():\n"
    "            if node.Class() == \"Group\":\n"
    "                return node\n"
    "    except Exception as exc:\n"
    "        _debug(\"paste failed: {0}\".format(exc))\n"
    "    finally:\n"
    "        if temp_path and os.path.exists(temp_path):\n"
    "            try:\n"
    "                os.unlink(temp_path)\n"
    "            except Exception:\n"
    "                pass\n"
    "    return None\n"
    "\n"
    "def _ensure_inputs(group):\n"
    "    group.begin()\n"
    "    try:\n"
    "        inputs = {node.name(): node for node in nuke.allNodes() if node.Class() == \"Input\"}\n"
    "\n"
    "        coverage_rig = inputs.get(\"coverage_rig\") or nuke.createNode(\"Input\")\n"
    "        coverage_rig.setName(\"coverage_rig\")\n"
    "        coverage_rig[\"number\"].setValue(2)\n"
    "\n"
    "        geo_input = inputs.get(\"geo\") or nuke.createNode(\"Input\")\n"
    "        geo_input.setName(\"geo\")\n"
    "        geo_input[\"number\"].setValue(3)\n"
    "\n"
    "        coverage_input = inputs.get(\"coverage_sheet\") or nuke.createNode(\"Input\")\n"
    "        coverage_input.setName(\"coverage_sheet\")\n"
    "        coverage_input[\"number\"].setValue(4)\n"
    "    finally:\n"
    "        group.end()\n"
    "\n"
    "def _ensure_update_knobs(group, update_script):\n"
    "    if not group.knob(\"charon_update_inputs\"):\n"
    "        update_knob = nuke.PyScript_Knob(\n"
    "            \"charon_update_inputs\",\n"
    "            \"Update Inputs\",\n"
    "            update_script or \"\",\n"
    "        )\n"
    "        update_knob.setFlag(nuke.STARTLINE)\n"
    "        group.addKnob(update_knob)\n"
    "\n"
    "    if not group.knob(\"charon_rig_cam_count\"):\n"
    "        cam_count_knob = nuke.Int_Knob(\"charon_rig_cam_count\", \"Projection Cameras Found\")\n"
    "        try:\n"
    "            cam_count_knob.setEnabled(False)\n"
    "        except Exception:\n"
    "            cam_count_knob.setFlag(nuke.DISABLED)\n"
    "        group.addKnob(cam_count_knob)\n"
    "\n"
    "def _current_cam_count(group):\n"
    "    group.begin()\n"
    "    try:\n"
    "        cams = [\n"
    "            node for node in nuke.allNodes()\n"
    "            if node.Class() in (\"Camera3\", \"Camera2\", \"Camera\")\n"
    "            and node.name().startswith(\"Cam\")\n"
    "        ]\n"
    "        return len(cams)\n"
    "    finally:\n"
    "        group.end()\n"
    "\n"
    "def _unique_name(base_name, names=None):\n"
    "    if names is None:\n"
    "        names = {node.name() for node in nuke.allNodes(recurseGroups=False)}\n"
    "    if base_name not in names:\n"
    "        return base_name\n"
    "    index = 1\n"
    "    while True:\n"
    "        candidate = \"{0}{1}\".format(base_name, index)\n"
    "        if candidate not in names:\n"
    "            return candidate\n"
    "        index += 1\n"
    "\n"
    "def _ensure_name_available(name, keep_node=None):\n"
    "    for other in nuke.allNodes(recurseGroups=False):\n"
    "        if other is keep_node:\n"
    "            continue\n"
    "        try:\n"
    "            if other.name() == name:\n"
    "                try:\n"
    "                    other.setName(_unique_name(\"{0}_OLD\".format(name)))\n"
    "                except Exception:\n"
    "                    pass\n"
    "        except Exception:\n"
    "            pass\n"
    "\n"
    "def _rebuild_for_count(group, count):\n"
    "    try:\n"
    "        count = int(count)\n"
    "    except Exception:\n"
    "        return None\n"
    "\n"
    "    template_path = os.path.join(TEMPLATE_DIR, \"projection_final_prep_{0}_cams.nk\".format(count))\n"
    "    template_path = os.path.normpath(template_path)\n"
    "    if not os.path.exists(template_path):\n"
    "        _debug(\"template not found: {0}\".format(template_path))\n"
    "        return None\n"
    "\n"
    "    script_content = _read_group_block(template_path)\n"
    "    if not script_content:\n"
    "        return None\n"
    "\n"
    "    def _collect_dependents(node):\n"
    "        deps = []\n"
    "        for other in nuke.allNodes(recurseGroups=False):\n"
    "            for i in range(other.inputs()):\n"
    "                try:\n"
    "                    if other.input(i) == node:\n"
    "                        deps.append((other, i))\n"
    "                except Exception:\n"
    "                    pass\n"
    "        return deps\n"
    "\n"
    "    input_nodes = [group.input(i) for i in range(group.inputs())]\n"
    "    old_name = group.name()\n"
    "    old_pos = (group.xpos(), group.ypos())\n"
    "    downstream = []\n"
    "    update_script = \"\"\n"
    "    update_knob = group.knob(\"charon_update_inputs\")\n"
    "    if update_knob:\n"
    "        try:\n"
    "            update_script = update_knob.value()\n"
    "        except Exception:\n"
    "            update_script = \"\"\n"
    "\n"
    "    root = nuke.root()\n"
    "    current_group = nuke.thisGroup()\n"
    "    root.begin()\n"
    "    try:\n"
    "        _debug(\"rebuild start: old_name={0} count={1}\".format(old_name, count))\n"
    "        downstream = _collect_dependents(group)\n"
    "        _debug(\"downstream count: {0}\".format(len(downstream)))\n"
    "        try:\n"
    "            group.setName(_unique_name(\"{0}_OLD\".format(old_name)))\n"
    "            _debug(\"old group renamed to: {0}\".format(group.name()))\n"
    "        except Exception as exc:\n"
    "            _debug(\"old group rename failed: {0}\".format(exc))\n"
    "\n"
    "        new_group = _paste_group(script_content)\n"
    "        if not new_group:\n"
    "            nuke.message(\"Failed to rebuild Final Prep group.\")\n"
    "            return None\n"
    "\n"
    "        for idx, inp in enumerate(input_nodes):\n"
    "            try:\n"
    "                new_group.setInput(idx, inp)\n"
    "            except Exception:\n"
    "                pass\n"
    "        for dep, idx in downstream:\n"
    "            try:\n"
    "                dep.setInput(idx, new_group)\n"
    "            except Exception:\n"
    "                pass\n"
    "        try:\n"
    "            new_group.setXYpos(old_pos[0], old_pos[1])\n"
    "        except Exception:\n"
    "            pass\n"
    "\n"
    "        _ensure_inputs(new_group)\n"
    "        _ensure_update_knobs(new_group, update_script)\n"
    "\n"
    "        try:\n"
    "            nuke.delete(group)\n"
    "        except Exception:\n"
    "            pass\n"
    "\n"
    "        try:\n"
    "            _ensure_name_available(old_name, new_group)\n"
    "            if new_group.name() != old_name:\n"
    "                try:\n"
    "                    new_group.setName(old_name)\n"
    "                except Exception:\n"
    "                    new_group.setName(_unique_name(old_name))\n"
    "        except Exception:\n"
    "            try:\n"
    "                if new_group.name() != old_name:\n"
    "                    new_group.setName(_unique_name(old_name))\n"
    "            except Exception:\n"
    "                pass\n"
    "        _debug(\"rename result: {0}\".format(new_group.name()))\n"
    "        try:\n"
    "            conflicts = [\n"
    "                node.fullName() if hasattr(node, \"fullName\") else node.name()\n"
    "                for node in nuke.allNodes(recurseGroups=True)\n"
    "                if node.Class() == \"Group\" and node.name().startswith(old_name)\n"
    "            ]\n"
    "            _debug(\"group name matches: {0}\".format(\", \".join(conflicts)))\n"
    "        except Exception:\n"
    "            pass\n"
    "        return new_group\n"
    "    finally:\n"
    "        if current_group and current_group is not root:\n"
    "            current_group.begin()\n"
    "\n"
    "def _camera_info(nodes, pivot):\n"
    "    info = []\n"
    "    for cam in nodes:\n"
    "        angle = _angle_from_name(cam.name())\n"
    "        if angle is None:\n"
    "            try:\n"
    "                angle = _angle_from_position(cam[\"translate\"].value(), pivot)\n"
    "            except Exception:\n"
    "                angle = 0.0\n"
    "        info.append((cam, angle))\n"
    "    return info\n"
    "\n"
    "def _collect_rig_data(rig):\n"
    "    rig.begin()\n"
    "    try:\n"
    "        target = nuke.toNode(\"Target\")\n"
    "        target_pos = target[\"translate\"].value() if target else None\n"
    "        cameras = [\n"
    "            node for node in nuke.allNodes()\n"
    "            if node.Class() in (\"Camera3\", \"Camera2\", \"Camera\")\n"
    "            and node.name().startswith(\"Cam\")\n"
    "        ]\n"
    "        cam_data = {node.name(): node[\"translate\"].value() for node in cameras}\n"
    "    finally:\n"
    "        rig.end()\n"
    "    return target_pos, cam_data\n"
    "\n"
    "def _update_rig_camera_count(group, rig):\n"
    "    _, cam_data = _collect_rig_data(rig)\n"
    "    count = len(cam_data)\n"
    "    knob = group.knob(\"charon_rig_cam_count\")\n"
    "    if knob is None:\n"
    "        knob = nuke.Int_Knob(\"charon_rig_cam_count\", \"Projection Cameras Found\")\n"
    "        try:\n"
    "            knob.setEnabled(False)\n"
    "        except Exception:\n"
    "            knob.setFlag(nuke.DISABLED)\n"
    "        group.addKnob(knob)\n"
    "    try:\n"
    "        knob.setValue(count)\n"
    "    except Exception:\n"
    "        try:\n"
    "            knob.setValue(int(count))\n"
    "        except Exception:\n"
    "            pass\n"
    "\n"
    "def _resolve_passthrough(start_node, max_hops=32):\n"
    "    current = start_node\n"
    "    visited = set()\n"
    "    hops = 0\n"
    "    while current and hops < max_hops:\n"
    "        if current in visited:\n"
    "            break\n"
    "        visited.add(current)\n"
    "        try:\n"
    "            if current.Class() not in (\"Dot\", \"NoOp\"):\n"
    "                return current\n"
    "        except Exception:\n"
    "            return current\n"
    "        try:\n"
    "            current = current.input(0)\n"
    "        except Exception:\n"
    "            current = None\n"
    "        hops += 1\n"
    "    return start_node\n"
    "\n"
    "def _find_group_input(group, input_name, class_names=None):\n"
    "    group.begin()\n"
    "    try:\n"
    "        input_node = nuke.toNode(input_name)\n"
    "        if not input_node or input_node.Class() != \"Input\":\n"
    "            return None\n"
    "        index = int(input_node[\"number\"].value()) if input_node.knob(\"number\") else 0\n"
    "    finally:\n"
    "        group.end()\n"
    "    node = group.input(index)\n"
    "    if not node:\n"
    "        return None\n"
    "    if class_names:\n"
    "        resolved = _find_upstream(node, class_names)\n"
    "        if resolved:\n"
    "            return resolved\n"
    "    return _resolve_passthrough(node)\n"
    "\n"
    "def _update_geo(group, geo_node):\n"
    "    if not geo_node:\n"
    "        return False\n"
    "    _debug(\"update_geo input: {0} ({1})\".format(geo_node.name(), geo_node.Class()))\n"
    "    if geo_node.Class() not in (\"ReadGeo2\", \"ReadGeo\"):\n"
    "        upstream = _find_upstream(geo_node, (\"ReadGeo2\", \"ReadGeo\"))\n"
    "        if upstream:\n"
    "            _debug(\"resolved upstream geo: {0} ({1})\".format(upstream.name(), upstream.Class()))\n"
    "            geo_node = upstream\n"
    "        else:\n"
    "            nuke.message(\"Geo input must be a ReadGeo/ReadGeo2 node.\")\n"
    "            return False\n"
    "\n"
    "    root = nuke.root()\n"
    "    current_group = nuke.thisGroup()\n"
    "    root.begin()\n"
    "    original_selection = list(nuke.selectedNodes())\n"
    "    for n in original_selection:\n"
    "        n.setSelected(False)\n"
    "    try:\n"
    "        geo_node.setSelected(True)\n"
    "        nuke.nodeCopy(\"%clipboard%\")\n"
    "        _debug(\"copied geo node: {0}\".format(geo_node.fullName() if hasattr(geo_node, \"fullName\") else geo_node.name()))\n"
    "    finally:\n"
    "        geo_node.setSelected(False)\n"
    "        for n in original_selection:\n"
    "            try:\n"
    "                n.setSelected(True)\n"
    "            except Exception:\n"
    "                pass\n"
    "        if current_group and current_group is not root:\n"
    "            current_group.begin()\n"
    "\n"
    "    group.begin()\n"
    "    try:\n"
    "        before_nodes = set(nuke.allNodes())\n"
    "        for n in nuke.selectedNodes():\n"
    "            n.setSelected(False)\n"
    "        nuke.nodePaste(\"%clipboard%\")\n"
    "        pasted_nodes = list(nuke.selectedNodes())\n"
    "        after_nodes = [node for node in nuke.allNodes() if node not in before_nodes]\n"
    "        if not after_nodes and not pasted_nodes:\n"
    "            nuke.message(\"Failed to paste geo node.\")\n"
    "            return False\n"
    "        _debug(\"pasted nodes: {0}\".format(\n"
    "            \", \".join(\"{0}({1})\".format(node.name(), node.Class()) for node in pasted_nodes)\n"
    "        ))\n"
    "        _debug(\"after_nodes: {0}\".format(\n"
    "            \", \".join(\"{0}({1})\".format(node.name(), node.Class()) for node in after_nodes)\n"
    "        ))\n"
    "\n"
    "        pasted = None\n"
    "        for node in pasted_nodes + after_nodes:\n"
    "            if node.Class() in (\"ReadGeo2\", \"ReadGeo\"):\n"
    "                pasted = node\n"
    "                break\n"
    "        if pasted is None:\n"
    "            pasted = (pasted_nodes or after_nodes)[0]\n"
    "        _debug(\"chosen pasted: {0} ({1})\".format(pasted.name(), pasted.Class()))\n"
    "        if pasted.knob(\"file\"):\n"
    "            try:\n"
    "                _debug(\"pasted file: {0}\".format(pasted[\"file\"].value()))\n"
    "            except Exception:\n"
    "                pass\n"
    "\n"
    "        existing_geos = [\n"
    "            node for node in nuke.allNodes()\n"
    "            if node.Class() in (\"ReadGeo2\", \"ReadGeo\")\n"
    "            and node is not pasted\n"
    "        ]\n"
    "        _debug(\"existing geos: {0}\".format(\n"
    "            \", \".join(\"{0}({1})\".format(node.name(), node.Class()) for node in existing_geos)\n"
    "        ))\n"
    "\n"
    "        def _is_clone(node):\n"
    "            try:\n"
    "                return bool(node.isClone())\n"
    "            except Exception:\n"
    "                return False\n"
    "\n"
    "        def _collect_connections(nodes):\n"
    "            connections = {node: [] for node in nodes}\n"
    "            for node in nuke.allNodes():\n"
    "                for i in range(node.inputs()):\n"
    "                    try:\n"
    "                        inp = node.input(i)\n"
    "                    except Exception:\n"
    "                        continue\n"
    "                    if inp in connections:\n"
    "                        connections[inp].append((node, i))\n"
    "            return connections\n"
    "\n"
    "        def _create_clone(master):\n"
    "            for n in nuke.selectedNodes():\n"
    "                n.setSelected(False)\n"
    "            master.setSelected(True)\n"
    "            before = set(nuke.allNodes())\n"
    "            if hasattr(nuke, \"clone\"):\n"
    "                try:\n"
    "                    nuke.clone(master)\n"
    "                except TypeError:\n"
    "                    nuke.clone()\n"
    "            else:\n"
    "                nuke.nodeCopy(\"%clipboard%\")\n"
    "                nuke.nodePaste(\"%clipboard%\")\n"
    "            created = [node for node in nuke.allNodes() if node not in before]\n"
    "            if created:\n"
    "                return created[0]\n"
    "            return None\n"
    "\n"
    "        if not existing_geos:\n"
    "            default_name = \"ReadGeo\" if geo_node.Class() == \"ReadGeo\" else \"ReadGeo2\"\n"
    "            try:\n"
    "                pasted.setName(default_name, unique=True)\n"
    "            except Exception:\n"
    "                pasted.setName(default_name)\n"
    "            _debug(\"created new geo: {0}\".format(pasted.name()))\n"
    "            return True\n"
    "\n"
    "        master_old = None\n"
    "        for node in existing_geos:\n"
    "            if node.name() in (\"ReadGeo2\", \"ReadGeo\"):\n"
    "                master_old = node\n"
    "                break\n"
    "        if master_old is None:\n"
    "            for node in existing_geos:\n"
    "                if not _is_clone(node):\n"
    "                    master_old = node\n"
    "                    break\n"
    "        if master_old is None:\n"
    "            master_old = existing_geos[0]\n"
    "\n"
    "        _debug(\"master_old: {0}\".format(master_old.name() if master_old else \"None\"))\n"
    "\n"
    "        geo_specs = []\n"
    "        for node in existing_geos:\n"
    "            try:\n"
    "                input_nodes = [node.input(i) for i in range(node.inputs())]\n"
    "            except Exception:\n"
    "                input_nodes = []\n"
    "            geo_specs.append({\n"
    "                \"node\": node,\n"
    "                \"name\": node.name(),\n"
    "                \"pos\": (node.xpos(), node.ypos()),\n"
    "                \"is_master\": node is master_old,\n"
    "                \"inputs\": input_nodes,\n"
    "            })\n"
    "        connections = _collect_connections([spec[\"node\"] for spec in geo_specs])\n"
    "\n"
    "        new_nodes = {}\n"
    "        for spec in geo_specs:\n"
    "            if spec[\"is_master\"]:\n"
    "                new_nodes[spec[\"node\"]] = pasted\n"
    "            else:\n"
    "                clone = _create_clone(pasted)\n"
    "                if clone:\n"
    "                    new_nodes[spec[\"node\"]] = clone\n"
    "                else:\n"
    "                    new_nodes[spec[\"node\"]] = pasted\n"
    "        _debug(\"created {0} geo nodes\".format(len(set(new_nodes.values()))))\n"
    "\n"
    "        for spec in geo_specs:\n"
    "            old_node = spec[\"node\"]\n"
    "            new_node = new_nodes.get(old_node)\n"
    "            if new_node is None:\n"
    "                continue\n"
    "            inputs = spec.get(\"inputs\", [])\n"
    "            for idx, inp in enumerate(inputs):\n"
    "                if inp is None:\n"
    "                    try:\n"
    "                        new_node.setInput(idx, None)\n"
    "                    except Exception:\n"
    "                        pass\n"
    "                    continue\n"
    "                replacement = new_nodes.get(inp, inp)\n"
    "                try:\n"
    "                    new_node.setInput(idx, replacement)\n"
    "                except Exception:\n"
    "                    pass\n"
    "\n"
    "        for old_node, new_node in new_nodes.items():\n"
    "            if old_node is new_node:\n"
    "                continue\n"
    "            for dep, idx in connections.get(old_node, []):\n"
    "                try:\n"
    "                    dep.setInput(idx, new_node)\n"
    "                except Exception:\n"
    "                    pass\n"
    "\n"
    "        for spec in geo_specs:\n"
    "            old_node = spec[\"node\"]\n"
    "            new_node = new_nodes.get(old_node)\n"
    "            if new_node is None:\n"
    "                continue\n"
    "            try:\n"
    "                new_node.setXYpos(spec[\"pos\"][0], spec[\"pos\"][1])\n"
    "            except Exception:\n"
    "                pass\n"
    "\n"
    "        for spec in geo_specs:\n"
    "            old_node = spec[\"node\"]\n"
    "            try:\n"
    "                nuke.delete(old_node)\n"
    "            except Exception:\n"
    "                pass\n"
    "\n"
    "        for spec in geo_specs:\n"
    "            new_node = new_nodes.get(spec[\"node\"])\n"
    "            if new_node is None:\n"
    "                continue\n"
    "            try:\n"
    "                new_node.setName(spec[\"name\"], unique=True)\n"
    "            except Exception:\n"
    "                try:\n"
    "                    new_node.setName(spec[\"name\"])\n"
    "                except Exception:\n"
    "                    pass\n"
    "\n"
    "        try:\n"
    "            geos = [node for node in nuke.allNodes() if node.Class() in (\"ReadGeo2\", \"ReadGeo\")]\n"
    "            _debug(\"geo nodes after update: {0}\".format(\n"
    "                \", \".join(\n"
    "                    \"{0}({1})\".format(node.name(), node[\"file\"].value() if node.knob(\"file\") else \"\")\n"
    "                    for node in geos\n"
    "                )\n"
    "            ))\n"
    "        except Exception:\n"
    "            pass\n"
    "        return True\n"
    "    finally:\n"
    "        group.end()\n"
    "\n"
    "def _update_cameras(group, rig):\n"
    "    target_pos, cam_data = _collect_rig_data(rig)\n"
    "    if not cam_data:\n"
    "        nuke.message(\"Coverage rig has no cameras named Cam*.\")\n"
    "        return False\n"
    "\n"
    "    group.begin()\n"
    "    try:\n"
    "        if target_pos is not None:\n"
    "            target = nuke.toNode(\"Target\")\n"
    "            if target:\n"
    "                target[\"translate\"].setValue(target_pos)\n"
    "\n"
    "        dest_cams = [\n"
    "            node for node in nuke.allNodes()\n"
    "            if node.Class() in (\"Camera3\", \"Camera2\", \"Camera\")\n"
    "            and node.name().startswith(\"Cam\")\n"
    "        ]\n"
    "        if not dest_cams:\n"
    "            nuke.message(\"Final Prep has no cameras named Cam*.\")\n"
    "            return False\n"
    "\n"
    "        dest_by_name = {node.name(): node for node in dest_cams}\n"
    "        used = set()\n"
    "        for name, translate_val in cam_data.items():\n"
    "            cam = dest_by_name.get(name)\n"
    "            if cam:\n"
    "                cam[\"translate\"].setValue(translate_val)\n"
    "                used.add(name)\n"
    "\n"
    "        remaining_src = [\n"
    "            (name, translate_val)\n"
    "            for name, translate_val in cam_data.items()\n"
    "            if name not in used\n"
    "        ]\n"
    "        if remaining_src:\n"
    "            pivot = target_pos if target_pos is not None else [0.0, 0.0, 0.0]\n"
    "            dest_info = _camera_info(\n"
    "                [node for node in dest_cams if node.name() not in used],\n"
    "                pivot,\n"
    "            )\n"
    "            remaining_src_info = []\n"
    "            for name, translate_val in remaining_src:\n"
    "                angle = _angle_from_name(name)\n"
    "                if angle is None:\n"
    "                    angle = _angle_from_position(translate_val, pivot)\n"
    "                remaining_src_info.append((name, translate_val, angle))\n"
    "\n"
    "            for name, translate_val, angle in sorted(remaining_src_info, key=lambda item: item[2]):\n"
    "                if not dest_info:\n"
    "                    break\n"
    "                best_index = None\n"
    "                best_delta = None\n"
    "                for idx, (cam, cam_angle) in enumerate(dest_info):\n"
    "                    delta = abs(angle - cam_angle)\n"
    "                    delta = min(delta, 360.0 - delta)\n"
    "                    if best_delta is None or delta < best_delta:\n"
    "                        best_delta = delta\n"
    "                        best_index = idx\n"
    "                cam, _ = dest_info.pop(best_index)\n"
    "                cam[\"translate\"].setValue(translate_val)\n"
    "        return True\n"
    "    finally:\n"
    "        group.end()\n"
    "\n"
    "def _run():\n"
    "    group = nuke.thisNode()\n"
    "    rig = _find_group_input(group, \"coverage_rig\", (\"Group\", \"Gizmo\", \"LiveGroup\"))\n"
    "    if not rig:\n"
    "        nuke.message(\"Connect Charon_Coverage_Rig to coverage_rig input.\")\n"
    "        return\n"
    "    if rig.Class() not in (\"Group\", \"Gizmo\", \"LiveGroup\"):\n"
    "        nuke.message(\"coverage_rig input must be a Group.\")\n"
    "        return\n"
    "    geo = _find_group_input(group, \"geo\")\n"
    "\n"
    "    rig_cam_count = len(_collect_rig_data(rig)[1])\n"
    "    current_cam_count = _current_cam_count(group)\n"
    "    _debug(\"rig_cam_count={0} current_cam_count={1} group={2}\".format(\n"
    "        rig_cam_count,\n"
    "        current_cam_count,\n"
    "        group.name(),\n"
    "    ))\n"
    "    if rig_cam_count and current_cam_count and rig_cam_count != current_cam_count:\n"
    "        _debug(\"rebuild for camera count: {0}\".format(rig_cam_count))\n"
    "        new_group = _rebuild_for_count(group, rig_cam_count)\n"
    "        if new_group:\n"
    "            group = new_group\n"
    "            rig = _find_group_input(group, \"coverage_rig\")\n"
    "            geo = _find_group_input(group, \"geo\")\n"
    "\n"
    "    _update_cameras(group, rig)\n"
    "    _update_rig_camera_count(group, rig)\n"
    "    if geo:\n"
    "        _update_geo(group, geo)\n"
    "\n"
    "_run()\n"
)


def final_prep_update_script() -> str:
    template_dir = os.path.join(paths.RESOURCE_DIR, "nuke_template")
    return _FINAL_PREP_UPDATE_SCRIPT.replace("__TEMPLATE_DIR__", template_dir)

